services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=auctions
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - 27018:27017
    volumes:
      - mongodata:/data/db
volumes:
  pgdata:
  mongodata: